import { useState, type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useAuth } from '../../../shared/auth/AuthProvider';
import { useWorkspace } from '../../../app/layouts/WorkspaceLayout';
import { Resource, useResource, Empty } from '../../../shared/ui/Resource';
import type { Attack, Character, Combo } from '../../project-workspace/types/product';
export function ComboWorkbench() {
  const { apiPath } = useWorkspace(); const [params] = useSearchParams();
  const resource = useResource<{ combos: Combo[] }>(apiPath + '/combos' + (params.get('character') ? '?character_id=' + encodeURIComponent(params.get('character')!) : ''));
  const data = useResource<{ characters: Character[] }>(apiPath + '/characters'); const attacks = useResource<{ attacks: Attack[] }>(apiPath + '/attacks');
  return <section data-page="combos"><h1>Combos</h1><p className="lead">Crie sequências com golpes do mesmo personagem.</p><Resource value={data} label="Não foi possível carregar os personagens do construtor.">{d => <Resource value={attacks} label="Não foi possível carregar os golpes do construtor.">{a => <ComboBuilder characters={d.characters} attacks={a.attacks} onSaved={resource.reload} />}</Resource>}</Resource><h2>Combos salvos</h2><Resource value={resource} label="Não foi possível carregar os combos.">{({ combos }) => combos.length ? combos.map(combo => <ComboCard key={combo.id} combo={combo} attacks={attacks.data?.attacks || []} reload={resource.reload} />) : <Empty>Nenhum combo salvo ainda. Use o construtor ou peça uma descoberta ao Combat Director.</Empty>}</Resource></section>;
}
function ComboBuilder({ characters, attacks, onSaved }: { characters: Character[]; attacks: Attack[]; onSaved: () => void }) {
  const { api } = useAuth(); const { apiPath } = useWorkspace(); const [character, setCharacter] = useState(''); const [steps, setSteps] = useState([{ attack_id: '', condition: 'on_hit' }]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const available = attacks.filter(a => !!character && a.character_id === character);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const form = event.currentTarget; try { await api.request(apiPath + '/combos', { method: 'POST', body: JSON.stringify({ name: new FormData(form).get('name'), character_id: character, source: 'USER_CREATED', steps: steps.map((step, index) => ({ ...step, index })) }) }); setMessage('Combo salvo. Execute uma análise para avaliar a sequência.'); onSaved(); } catch { setMessage('Não foi possível salvar. Confira se os golpes pertencem ao personagem.'); } finally { setBusy(false); } }
  return <form className="card" onSubmit={submit}><h2>Construtor de combo</h2><label>Nome do combo<input name="name" required maxLength={120} /></label><label>Personagem<select required value={character} onChange={e => { setCharacter(e.target.value); setSteps([{ attack_id: '', condition: 'on_hit' }]); }}><option value="">Selecione um personagem</option>{characters.map(c => <option key={c.id} value={c.id}>{c.display_name || c.name}</option>)}</select></label>{steps.map((step, index) => <div className="step" key={index}><label>Golpe {index + 1}<select required value={step.attack_id} onChange={e => setSteps(steps.map((s, i) => i === index ? { ...s, attack_id: e.target.value } : s))}><option value="">Selecione um golpe</option>{available.map(a => <option key={a.attack_id} value={a.attack_id}>{a.name} · {a.damage} dano</option>)}</select></label><label>Condição<select value={step.condition} onChange={e => setSteps(steps.map((s, i) => i === index ? { ...s, condition: e.target.value } : s))}><option value="on_hit">Ao acertar</option><option value="on_block">No bloqueio</option><option value="always">Sempre</option></select></label>{steps.length > 1 && <button type="button" aria-label={'Remover golpe ' + (index + 1)} onClick={() => setSteps(steps.filter((_, i) => i !== index))}>Remover</button>}</div>)}{character && !available.length && <p>Nenhum golpe associado a este personagem. Importe seus golpes primeiro.</p>}<div className="actions"><button type="button" onClick={() => setSteps([...steps, { attack_id: '', condition: 'on_hit' }])} disabled={!available.length}>Adicionar golpe</button><button type="submit" className="primary" disabled={busy || !available.length}>{busy ? 'Salvando…' : 'Salvar combo'}</button></div><p role="status">{message}</p></form>;
}
function ComboCard({ combo, attacks, reload }: { combo: Combo; attacks: Attack[]; reload: () => void }) {
  const { apiPath } = useWorkspace(); const { api } = useAuth(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <article className="card"><span className="badge">{combo.source === 'AI_DISCOVERED' ? 'Descoberto por IA' : combo.source === 'IMPORTED' ? 'Importado' : 'Criado por designer'}</span><h3>{combo.name}</h3><ol>{combo.steps.map((s, i) => <li key={i}>{attacks.find(a => a.attack_id === s.attack_id)?.name || s.attack_id} · {s.condition}</li>)}</ol>{combo.notes && <p>{combo.notes}</p>}<button type="button" disabled={busy} onClick={async () => { if (!confirm('Excluir este combo?')) return; setBusy(true); try { await api.request(apiPath + '/combos/' + encodeURIComponent(combo.id), { method: 'DELETE' }); reload(); } catch { setError('Não foi possível excluir o combo.'); } finally { setBusy(false); } }}>Excluir combo</button>{error && <p role="alert">{error}</p>}</article>;
}
