import { useState, type FormEvent } from 'react';
import { useAuth } from '../../../shared/auth/AuthProvider';
import { useWorkspace } from '../../../app/layouts/WorkspaceLayout';
import { Resource, useResource, Empty } from '../../../shared/ui/Resource';
import type { Analysis, Attack } from '../../project-workspace/types/product';
export function AnalysisWorkbench() {
  const { api } = useAuth(); const { apiPath } = useWorkspace(); const resource = useResource<{ analyses: Analysis[] }>(apiPath + '/analyses'); const attacks = useResource<{ attacks: Attack[] }>(apiPath + '/attacks'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api.request(apiPath + '/analyses', { method: 'POST', body: JSON.stringify({ subject: data.get('subject'), target_attack_id: data.get('attack') || undefined }) }); resource.reload(); } catch { setError('Não foi possível executar a análise. Confira os dados do projeto.'); } finally { setBusy(false); } }
  return <section data-page="analysis"><h1>Análises</h1><p className="lead">Diagnósticos e recomendações para orientar suas decisões.</p><Resource value={attacks} label="Não foi possível carregar os golpes para análise.">{data => <form className="card" onSubmit={submit}><h2>Solicitar análise</h2><label>Objetivo<input name="subject" required placeholder="Ex.: avaliar risco e contrajogo" /></label><label>Golpe<select name="attack"><option value="">Combate do projeto</option>{data.attacks.map(a => <option value={a.attack_id} key={a.attack_id}>{a.name}</option>)}</select></label>{error && <p role="alert" className="error">{error}</p>}<button type="submit" disabled={busy} className="primary">{busy ? 'Analisando…' : 'Executar análise'}</button></form>}</Resource><Resource value={resource} label="Não foi possível carregar as análises.">{({ analyses }) => analyses.length ? analyses.map(an => <article className="card" key={an.id}><h2>{an.subject}</h2><h3>Achados</h3>{an.findings.length ? an.findings.map((f, i) => <div key={i}><span className="badge">{f.severity}</span><h4>{f.title}</h4><p>{f.description}</p></div>) : <p>Nenhum problema identificado nesta análise.</p>}<h3>Recomendações</h3>{an.recommendations.map((r, i) => <div key={i}><h4>{r.title}</h4><p>{r.description}</p><p>{r.suggested_action}</p></div>)}</article>) : <Empty>Nenhuma análise registrada ainda.</Empty>}</Resource></section>;
}
