import { useState, type FormEvent } from 'react';
import { useAuth } from '../../../shared/auth/AuthProvider';
import { useWorkspace } from '../../../app/layouts/WorkspaceLayout';
export function ImportPage() {
  const { api } = useAuth(); const { apiPath, workspace } = useWorkspace(); const [text, setText] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<{ asset_count?: number; accepted?: number; quarantined_count?: number; characters_count?: number }>();
  async function submit(event: FormEvent) {
    event.preventDefault(); setError(''); setResult(undefined); setBusy(true);
    try { const bundle = JSON.parse(text); if (!bundle.manifest || !bundle.files) throw new Error('format'); bundle.manifest.workspace_id = workspace.id; const data = await api.request<{ asset_count?: number; accepted?: number; quarantined_count?: number; characters_count?: number }>(apiPath + '/bundles', { method: 'POST', body: JSON.stringify(bundle) }); setResult(data); }
    catch { setError('Não foi possível importar. Confira o formato JSON, o manifesto, os arquivos e os limites do bundle.'); } finally { setBusy(false); }
  }
  return <section data-page="import"><h1>Importar Dados</h1><p className="lead">Traga os dados do seu jogo para o workbench.</p><article className="card"><h2>1. Prepare o bundle na Unity</h2><p>Baixe o script C# e coloque-o em Assets/Editor. Prepare o manifesto e os arquivos de combate exportados em JSON.</p><a className="button" href="/assets/CombatDesignerExporter.cs" download>Baixar script C#</a><p className="muted">O script atual fornece as funções de manifesto e checksums. A coleta dos assets deve ser adaptada ao seu projeto Unity.</p></article><form className="card" onSubmit={submit}><h2>2. Envie os dados</h2><label>Arquivo JSON<input type="file" accept=".json,application/json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024) { setError('O arquivo excede o limite de 10 MB.'); return; } setText(await file.text()); }} /></label><label>Conteúdo do bundle<textarea required rows={10} value={text} onChange={e => setText(e.target.value)} placeholder="Cole o JSON do bundle exportado" /></label>{error && <p role="alert" className="error">{error}</p>}<button type="submit" className="primary" disabled={busy || !text.trim()}>{busy ? 'Importando…' : 'Importar bundle'}</button></form>{result && <article className="card" role="status"><h2>Importação concluída</h2><p>Dados reconhecidos: {result.asset_count ?? result.accepted ?? 'consulte os golpes do projeto'}</p>{result.characters_count !== undefined && <p>Personagens: {result.characters_count}</p>}{result.quarantined_count !== undefined && <p>Itens que precisam de revisão: {result.quarantined_count}</p>}</article>}</section>;
}
