import { Link, useSearchParams } from 'react-router-dom';
import { useWorkspace } from '../../../app/layouts/WorkspaceLayout';
import { Resource, useResource, Empty } from '../../../shared/ui/Resource';
import type { Attack, Character } from '../../project-workspace/types/product';
export function AttackCatalog() {
  const { apiPath, base, selectedAttacks, setSelectedAttacks } = useWorkspace(); const [params, setParams] = useSearchParams();
  const resource = useResource<{ attacks: Attack[] }>(apiPath + '/attacks'); const chars = useResource<{ characters: Character[] }>(apiPath + '/characters');
  const character = params.get('character') || ''; const query = params.get('q') || '';
  function filter(key: string, value: string) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next); }
  return <section data-page="attacks"><h1>Golpes</h1><p className="lead">Compare frame data e selecione golpes para investigar com o Director.</p><div className="filters"><label>Buscar golpe<input value={query} onChange={e => filter('q', e.target.value)} /></label><label>Personagem<select value={character} onChange={e => filter('character', e.target.value)}><option value="">Todos os personagens</option>{chars.data?.characters.map(c => <option key={c.id} value={c.id}>{c.display_name || c.name}</option>)}</select></label></div>{chars.error && <p role="alert">Não foi possível carregar o filtro de personagens. <button type="button" onClick={chars.reload}>Tentar novamente</button></p>}<Resource value={resource} label="Não foi possível carregar os golpes.">{({ attacks }) => {
    const items = attacks.filter(a => (!character || a.character_id === character) && a.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
    return items.length ? <div className="table-scroll"><table><caption>{items.length} golpes encontrados</caption><thead><tr>{['Selecionar', 'Golpe', 'Personagem', 'Startup', 'Ativo', 'Recovery', 'Dano', 'Cancelamento'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{items.map(a => <tr key={a.attack_id}><td><input aria-label={'Selecionar ' + a.name} type="checkbox" checked={selectedAttacks.includes(a.attack_id)} onChange={e => setSelectedAttacks(e.target.checked ? [...selectedAttacks, a.attack_id] : selectedAttacks.filter(id => id !== a.attack_id))} /></td><td>{a.name}</td><td>{chars.data?.characters.find(c => c.id === a.character_id)?.name || 'Sem personagem'}</td><td>{a.startup_frames}f</td><td>{a.active_frames}f</td><td>{a.recovery_frames}f</td><td>{a.damage}</td><td>{a.cancel_window ? `${a.cancel_window.start_frame}–${a.cancel_window.end_frame}f` : '—'}</td></tr>)}</tbody></table></div> : <Empty><p>Nenhum golpe encontrado.</p><Link to={base + '/import'}>Importar dados</Link></Empty>;
  }}</Resource><div className="actions"><Link className="button" to={base + '/director'}>Conversar sobre {selectedAttacks.length} golpe(s)</Link><Link className="button secondary" to={base + '/simulation'}>Simular combate</Link></div></section>;
}
