import { test, expect } from '@playwright/test';
test('served UI creates, renames, opens, populates and archives a project', async ({ page }) => {
  await page.goto('/register'); await page.getByLabel('Nome de usuário').fill('crud_' + crypto.randomUUID().slice(0, 12)); await page.getByLabel('Senha', { exact: true }).fill('ActionsTest123!'); await page.getByRole('button', { name: 'Criar conta', exact: true }).click();
  await expect(page).toHaveURL(/\/workspaces$/); await page.getByText('Criar projeto', { exact: true }).first().click(); await page.getByLabel('Nome do projeto').fill('Meu jogo'); await page.getByRole('button', { name: 'Criar projeto', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Meu jogo', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Renomear' }).click(); await page.getByLabel('Novo nome').fill('Arena'); await page.getByRole('button', { name: 'Salvar nome' }).click(); await expect(page.getByRole('heading', { name: 'Arena', exact: true })).toBeVisible();
  await page.getByRole('link', { name: /Abrir projeto/ }).click(); await expect(page.locator('[data-page="overview"]')).toBeVisible(); const base = new URL(page.url()).pathname;
  await page.getByRole('navigation', { name: 'Navegação do projeto' }).getByRole('link', { name: 'Personagens', exact: true }).click(); await page.getByText('Cadastrar personagem', { exact: true }).click(); await page.getByLabel('Nome do personagem').fill('Lutador Ágil'); await page.getByLabel('Arquétipo').fill('Rushdown'); await page.getByRole('button', { name: 'Cadastrar', exact: true }).click();
  await page.getByRole('link', { name: 'Lutador Ágil' }).click(); await expect(page.getByRole('heading', { name: 'Lutador Ágil' })).toBeVisible();
  await page.goto('/workspaces'); page.on('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: 'Arquivar', exact: true }).click(); await expect(page.getByText('unity · Arquivado')).toBeVisible(); await page.goto(base); await expect(page.getByRole('heading', { name: 'Projeto arquivado' })).toBeVisible();
});
test('real combo, analysis and simulation capabilities survive the routing migration', async ({ page, request }) => {
  const registration = await request.post('/api/auth/register', { data: { username: 'features_' + crypto.randomUUID().slice(0, 12), password: 'ActionsTest123!' } }); const user = await registration.json();
  const created = await request.post('/api/workspaces', { headers: { Authorization: 'Bearer ' + user.access_token }, data: { name: 'Test Combat', seed_demo_data: true } }); const workspace = await created.json(); const base = '/workspaces/' + workspace.id;
  await page.addInitScript(user => { localStorage.setItem('cd_access_token', user.access_token); localStorage.setItem('cd_refresh_token', user.refresh_token); }, user);
  await page.goto(base + '/combos'); await page.getByLabel('Nome do combo').fill('Combo teste'); await page.getByLabel('Personagem', { exact: true }).selectOption('char_default'); await page.getByLabel('Golpe 1', { exact: true }).selectOption({ index: 1 }); await page.getByRole('button', { name: 'Salvar combo' }).click(); await expect(page.getByRole('heading', { name: 'Combo teste' })).toBeVisible();
  await page.goto(base + '/analysis'); await page.getByLabel('Objetivo').fill('Avaliar golpe'); await page.getByLabel('Golpe', { exact: true }).selectOption({ index: 1 }); await page.getByRole('button', { name: 'Executar análise' }).click(); await expect(page.getByRole('heading', { name: 'Avaliar golpe' })).toBeVisible();
  await page.goto(base + '/simulation'); await page.getByRole('button', { name: 'Executar simulação' }).click(); await expect(page.getByRole('heading', { name: 'Resultado da simulação' })).toBeVisible();
});
