import { useState, type FormEvent } from 'react';
import { useAuth } from '../../../shared/auth/AuthProvider';
import { useWorkspace } from '../../../app/layouts/WorkspaceLayout';
import { useResource, Resource, Empty } from '../../../shared/ui/Resource';
import type { Attack } from '../../project-workspace/types/product';
interface Simulation { simulation_id: string; status: string; total_frames: number; events: { frame: number; type: string; actor_id?: string; details?: { damage?: number } }[] }
export function SimulationWorkbench() {
  const { api } = useAuth(); const { apiPath, workspace } = useWorkspace(); const attacks = useResource<{ attacks: Attack[] }>(apiPath + '/attacks'); const [result, setResult] = useState<Simulation>(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); setResult(undefined); const budget = { max_frames: Number(data.get('frames')), max_iterations: 5000 }; try { const response = await api.request<{ simulation: Simulation }>(apiPath + '/simulations', { method: 'POST', body: JSON.stringify({ workspace_id: workspace.id, scenario: { scenario_id: 'designer-duel', actors: [{ actor_id: 'hero', team: 1, initial_health: 100, attack_ids: [data.get('attack')] }, { actor_id: 'dummy', team: 2, initial_health: 100, attack_ids: [] }], budget, tick_rate: 60 }, config: { budget, tick_rate: 60 } }) }); setResult(response.simulation); } catch { setError('Não foi possível executar a simulação.'); } finally { setBusy(false); } }
  return <section data-page="simulation"><h1>Simulação</h1><p className="lead">Explore a linha do tempo de um confronto.</p><Resource value={attacks} label="Não foi possível carregar os golpes para simular.">{data => data.attacks.length ? <form className="card" onSubmit={submit}><label>Golpe<select name="attack" required>{data.attacks.map(a => <option key={a.attack_id} value={a.attack_id}>{a.name}</option>)}</select></label><label>Limite de frames<input type="number" name="frames" min={1} max={3600} defaultValue={120} required /></label><button disabled={busy} className="primary">{busy ? 'Simulando…' : 'Executar simulação'}</button></form> : <Empty>Importe golpes antes de simular o combate.</Empty>}</Resource>{error && <p role="alert" className="error">{error}</p>}{result ? <article className="card"><h2>Resultado da simulação</h2><p>{result.status} · {result.total_frames} frames</p><ol>{result.events.map((event, i) => <li key={i}>Frame {event.frame} · {event.type}{event.details?.damage !== undefined ? ` · ${event.details.damage} dano` : ''}</li>)}</ol></article> : !busy && <p className="muted">Execute um cenário para visualizar os eventos.</p>}</section>;
}
