import { Link } from 'react-router-dom';
import { useWorkspace } from '../../../app/layouts/WorkspaceLayout';
import { useResource, Resource, Empty } from '../../../shared/ui/Resource';
import type { Overview } from '../types/product';
import { Onboarding } from '../../help/components/HelpCenterPage';
export function WorkspaceOverview() {
  const { apiPath, base } = useWorkspace(); const resource = useResource<Overview>(apiPath + '/overview');
  return <section data-page="overview"><h1>Visão Geral</h1><Onboarding /><Resource value={resource} label="Não foi possível carregar o resumo do projeto.">{data => <>{!data.has_data && <Empty><h2>Seu projeto está pronto para começar</h2><p>Importe os dados de combate para explorar golpes, personagens e combos.</p><Link className="button primary" to={base + '/import'}>Importar dados</Link></Empty>}<div className="kpis">{[['characters_count', 'Personagens'], ['attacks_count', 'Golpes'], ['combos_count', 'Combos'], ['analyses_count', 'Análises'], ['unassigned_attacks_count', 'Golpes sem personagem'], ['mechanical_issues_count', 'Problemas detectados'], ['average_combo_damage', 'Dano médio dos combos'], ['max_combo_damage', 'Dano máximo dos combos']].map(([key, label]) => <article className="card" key={key}><strong className="kpi">{data.kpis[key] ?? '—'}</strong><span>{label}</span></article>)}</div><h2>Próximos passos</h2><div className="actions">{[['combos', 'Criar combo manual'], ['analysis', 'Analisar golpe'], ['director', 'Perguntar ao Combat Director'], ['import', 'Importar dados']].map(([path, title]) => <Link className="button secondary" key={path} to={base + '/' + path}>{title}</Link>)}</div><h2>Atividade recente</h2>{data.recent_activity.length ? <ul className="activity">{data.recent_activity.map(item => <li key={item.id}>{item.label}</li>)}</ul> : <Empty>Nenhuma atividade ainda.</Empty>}<h2>Recomendações recentes</h2>{data.recent_recommendations.length ? data.recent_recommendations.map(item => <article className="card" key={item.id}><h3>{item.title}</h3><p>{item.description}</p><p>{item.suggested_action}</p></article>) : <p className="muted">As recomendações aparecerão após suas análises.</p>}</>}</Resource></section>;
}
